src/gadgets/nonnative/bn/big_uint_mul_mod_chip/mod.rs, src/gadgets/nonnative/bn/big_uint_mul_mod_chip/tests.rs
Impl `red_mod` function in the `big_uint_mul_mod_chip` module. The new function takes
assigned cells as parameters and performs modulus reduction. The result is
returned as instance of `ModOperationResult` containing the quotient and remainder.
Close #44
=> feat(bn): impl `red_mod`

src/gadgets/ecc.rs, src/plonk/mod.rs, src/poseidon/poseidon_hash.rs, src/util.rs
refactor(util): return `Option` instead of panic
feat(util): Handle potential errors in field conversions
Part of #41
=> refactor(util): rm unnecessary borrow of ownership

src/nifs.rs, src/plonk/mod.rs, src/polynomial/mod.rs
We still identify `u` as of Challenge type in Expression without introduce extra type. However, in order to make the logic of folding more consistency, we separate homogeneous `u` from `challenges` in `RelaxedPlonkInstance`.  Another reason for separation is that the folding of `u` doesn't need BigNat operation which makes the code less confusion.
=> refactor(plonk): separate homogenous u from challenges

src/gadgets/nonnative/bn/big_uint_mul_mod_chip/mod.rs, src/gadgets/nonnative/bn/big_uint_mul_mod_chip/tests.rs
Since we need this method in fold process, it is taken to public. The `rhs` type has been changed to a more general one as well
fix(bn): add input max word into `red_mod`
Close #62
=> feat(bn): make `assign_sum` pub

src/gadgets/ecc.rs
Cleaned up a little anti-pattern
=> fix(ecc): `&Vec<_>` -> `&[_]`

src/nifs.rs, src/plonk/lookup.rs, src/plonk/mod.rs, src/poseidon/mod.rs, src/poseidon/poseidon_hash.rs
- rm borrow ownership from `absorb_point` in random oracle (separate commit, for easy filter other changes)
- rm duplication of lookup arguments coefficients calc logic
- rm unnecessary `self` from some `eval` fn
- made `run_sps_protocol` internal functions simpler by rm code duplication
- fix issue with lazy `.map` without any collect at the end, in sps functions
The question that bothers me is what is the guaranteed lookup_argument inside _2-_3 functions, as there is about to be panic inside. Some of the logic may depend on that.
I suggest these changes as a discussion
=> refactor(sps): proposal with refactoring of rounds fn

src/gadgets/nonnative/bn/big_uint_mul_mod_chip/mod.rs, src/gadgets/util.rs, src/ivc/fold_relaxed_plonk_instance_chip.rs, src/main_gate.rs
- `q_m: Column<Fixed> -> q_m: [Column<Fixed>; 2]`
- Add summand to main gate: `q_m[1]*s[2]*s[3]` if `T >= 4`
Part of #77
@chaosma Please check tests asserts in `main_gate` module
=> feat(mg): extra mult

src/gadgets/nonnative/bn/big_uint_mul_mod_chip/mod.rs, src/gadgets/nonnative/bn/big_uint_mul_mod_chip/tests.rs
Instead of just checking that the value fits into bits, we change the return type and are able to get those bits as a cells.
=> feat(bn): `check_fits_in_bits` -> `decompose_in_bits`

src/constants.rs, src/gadgets/ecc.rs, src/ivc/fold_relaxed_plonk_instance_chip.rs, src/main_gate.rs, src/poseidon/mod.rs, src/poseidon/poseidon_circuit.rs, src/poseidon/poseidon_hash.rs, src/util.rs
By using `NonZero` we eliminate a class of errors where you don't get errors with zero length (e.g. traversing arrays with zero length just doesn't happen), however, no work is done and the data at the end is incorrect.
It also allows us to better reflex some places where we pass the size of some collection as a parameter and the collection turns out to be empty due to an error. Now at least we will get panic in such places
=> Use `NonZeroUsize` for constants

src/ivc/fold_relaxed_plonk_instance_chip.rs
In anticipation of the rest of the tests, the current state has been refactored and the number of fold rounds for testing has been expanded. The last change is significant for example for `fold_E`, which passed for one round of folding (because `r` was `u128` and `r ^ 2` in both fields was the same), but for two rounds already gave an error.
=> test(ivc): improve fold tests fixtures

src/main_gate.rs, src/nifs/mod.rs, src/plonk/eval.rs, src/polynomial/mod.rs
Previously, a tuple of three interrelated elements such as rotation & index column & type of var was used. Such a tuple is much simpler to express with enum
As refactoring for #80
=> refactor(poly): tuple -> struct for col index

src/gadgets/ecc.rs
This is a first quick optimization by removing the condition check for p equals infinity point. We will continue optimising the `fn scalar_mul_opt` and update the issue #77
=> feat(ecc): optimize ecc scalar mul

src/nifs/tests.rs, src/plonk/mod.rs, src/plonk/util.rs, src/polynomial/sparse.rs
This PR fixed issues in `is_sat_perm`
*  correct calculation of instance column index: previously it assumes the index is always 0, but the actual index depends on the developer input
*  the columns in permutation need exclude instance column when instance column is none
* When the special soundness protocol has round equals one, the `W.W[0]` is no longer witness columns, we can slice with correct length to uniform different round numbers.
Close #91
=> fix `is_sat_perm`

src/gadgets/nonnative/bn/big_uint_mul_mod_chip/mod.rs
There was a bug if exactly limbs_count of elements was obtained while calculating the sum, then panic on `split_at` would fall. Now this check for zero tail is optional.
=> fix(bn): limbs limit in `assign_sum`

src/ivc/fold_relaxed_plonk_instance_chip.rs, src/util.rs
Docs & test & logs for `fold_instances`
Part of #32
=> test(ivc): impl `fold_instances_test`

.github/workflows/rust.yml
Due to the squash policy, PRs will be more granular, so there will be a situation of chains of PRs going into each other. To make it easier to work with this, you can enable CI on any PR. For an open-source project this will not be expensive.
=> ci: turn on workflow for all PR

src/ivc/fold_relaxed_plonk_instance_chip.rs
=> fix(ivc): bits instead of limbs in fold-instances

Cargo.toml, src/gadgets/nonnative/bn/big_uint.rs, src/gadgets/nonnative/bn/big_uint_mul_mod_chip/mod.rs, src/ivc/fold_relaxed_plonk_instance_chip.rs, src/lib.rs
chore: add dep `result_inspect`
There are three common approaches to check errors trace:
- Errors include full & detailed annotations of the situation (e.g. on which variable the error occurred by str).
- Included execution traces (something like `backtrace` for panic, only for errors, can be added automaticly by 'thiserror' crate).
- Logs with context
The first one is the best, but requires a lot of dev-work, the second one is simpler, but is redundant for debugging, because every error will bring with it a callstack. The third is the most temporary, however, the fastest to add and, most importantly, to migrate to any of the above two methods.
Therefore, for the speed of work at this stage, I suggest just logging the error trace, and then migrate to one of the designs above.
=> refactor: integrate `inspect_err`

src/gadgets/nonnative/bn/big_uint.rs, src/ivc/fold_relaxed_plonk_instance_chip.rs, src/ivc/step_circuit.rs, src/plonk/mod.rs
This PR introduces significant refinements to the IVC folding chip, enhancing its usability and maintainability. Key changes include restructuring the chip's fields and improving test fixtures for better abstraction and readability. Here's a breakdown of the specific updates:
The `big uint chip` has been integrated into the `self` structure, leading to a more streamlined argument structure in the fold-chip methods. This change simplifies the method interfaces by reducing the number of arguments required.
The configuration details have also been moved into the self structure, further decluttering the method interfaces and making the chip more self-contained.
This new structure is returned from the chip and simplifies the `AssignedWitness` structure. It represents a significant step towards …
=> feat(ivc): finalize fold chip 

src/gadgets/ecc.rs, src/ivc/fold_relaxed_plonk_instance_chip.rs, src/ivc/incrementally_verifiable_computation.rs, src/ivc/step_circuit.rs
This PR introduces significant improvements to the IVC algorithm, focusing on the implementation of conditional selection between base and non-base cases, and refining the ECC component. 
Here's a breakdown of the changes:
A new feature is introduced to handle the selection between base and non-base cases in the IVC process. At step zero our task is simply to generate a relaxed plonk instance, and at any other step to commit folding. But we are running on-circuit, so we perform both of these actions each time, and then choose one of the options depending on the step.
Implemented a method to synthesize steps specifically for the base case of IVC. That is, make a call to the key folding-chip inside the `StepCircutiExt` abstraction. This is a preparation for synthesizing the step circuit …
=> feat(ivc): impl ext::synthesize_step_non_base_case

Cargo.toml, src/commitment.rs, src/constants.rs, src/digest.rs, src/lib.rs
In #111 @chaosma suggested just porting the module from Nova, however, I've rethought it into a more elegant and usable form. 
Also the constant `NUM_HASH_BITS` has been changed, let me know if I misunderstood its intent and it should be 250 there
This is rethought of Nova module: https://github.com/microsoft/Nova/src/digest.rs
=> feat(digest): impl `digest_to_f` ext

src/ivc/fold_relaxed_plonk_instance_chip.rs, src/ivc/step_circuit.rs, src/main_gate.rs, src/poseidon/mod.rs, src/poseidon/poseidon_circuit.rs
- feat(ivc): finalize `StepCircuitExt::synthesize`
- feat(mg): impl `WrapValue::from_assigned_point`
- feat(ivc): `AssignedRelaxedPlonkInstance::absorb_into`
- feat(ivc): add assigned input witness into folding result
Finalized 'StepCircuitExt', the result now includes all the context needed for subsequent IVC work.
Part of #32
=> feat(ivc): finalize `StepCircuitExt::synthesize`

src/nifs/tests.rs, src/poseidon/poseidon_hash.rs, src/util.rs
**Why?**
While implementing IVC I needed to link two random oracle - off-circuit & on-circuit. I created a new trait that allows you to bind from and saw the redundancy in the type definition. It makes no sense to have `F` which is equal to `C::Base`, you can use `C::Base` itself
Since this affects a component outside of IVC, I've separated these changes into a separate PR
**What?**
Refactoring: remove extra generic type from `ROTrait`
**How?**
**Before**
```rust
pub struct PoseidonHash<
C: CurveAffine<Base = F>,
F: PrimeField + FromUniformBytes<64>,
const T: usize,
const RATE: usize,
>
```
**After**
```rust
pub struct PoseidonHash<C: CurveAffine, const T: usize, const RATE: usize>
where
C::Base: ff::PrimeFieldBits + ff::FromUniformBytes<64>,
```
=> refactor(poseidon): rm excessive generic

src/ivc/fold_relaxed_plonk_instance_chip.rs, src/nifs/mod.rs, src/nifs/tests.rs
In previous implementation, we use fixed_commitment to represent circuit information which is not enough. We have to include custom gates and other necessary metadata. See issue #85.
To do so, we implemented digest method to calculate the hash of public parameters, see #112 
We can pass the digest hash as parameter to the `NIFS::prove` and `NIFS::verify`. However, there is one minor difficulty is that we have to represent the hash we generate as BigInt limbs. It turned out we can easily solve this by commit the hash (as scalar) to a point in ECC curve.   
There are still work left to be done in future PR/PRs: 
(1) change `digest_to_f` to `digest_to_curve`, which can be simply achieved by one ecc scalar mul: `digest=hash_digest*commitment_key[0]`.
(2) remove the unnecessary …
=> feat(nifs): pass `pp_digest` as parameter

src/digest.rs
To make it easier to operate with a hash of public parameters, part of #85, we added `digest_to_curve`.
One minor modification is that instead of using a commitment key, we can fix the point to be the generator of the curve. This simplifies our function. It will be safe as long as the number of bits is less than the size of the scalar curve of the field.
=> feat(digest): impl digest_to_curve

Cargo.toml, src/ivc/fold_relaxed_plonk_instance_chip.rs, src/poseidon/mod.rs, src/poseidon/poseidon_circuit.rs, src/poseidon/poseidon_hash.rs, src/poseidon/random_oracle.rs, src/poseidon/spec.rs, src/util.rs
**Why?**
We need to serialize public params in order to commit pp at the IVC level. One of the most important parameters we need to serialize are constants for random oracle, which are an external type in our project. We need to wrap it in a local type and provide serialization.
There are two approaches:
- Commit `r_f` & `r_p` from which Spec is created
- Commit all constants
This is an implementation of the second approach, since the first approach makes us dependent on a particular implementation of parameter generation. But perhaps we can rely on him to avoid such redundant wrapping. Feel free to discuss the topic.
**What?**
- Allocation of all traits in the poseidon module into a separate module (like `ROTrait`, `ROCircuitTrait`, `ROPair` etc)
- Allocation of a separate 'spec' module …
=> feat(poseidon): serialize `Spec`

examples/sha256/main.rs, src/commitment.rs, src/ivc/incrementally_verifiable_computation.rs, src/ivc/mod.rs, src/ivc/public_params.rs, src/ivc/step_circuit.rs, src/nifs/tests.rs, src/nifs/vanilla.rs, src/plonk/lookup.rs, src/plonk/mod.rs, src/polynomial/mod.rs, src/poseidon/mod.rs, src/poseidon/random_oracle.rs, src/table.rs
**Why?**
Close #85 
**What?**
- impl `PulicParams::new`
- impl `PublicParams::serialize`
- create `pulic_params` module
**How?**
In https://github.com/snarkify/halo2/pull/6#issuecomment-1903237566 @chaosma propose instead of serialization `TableData` fold in first into `PlonkStructure`. This PR is the epitome of that idea.
One nuance of the implementation is that `plonk_structure` can be created only for `Scalar` field, so we need to have paired curves for serialization, so it is done at the highest level of `PublicParams` rather than at the `CircuitPublicParams` level
Since the code will turn out to be voluminous, it is allocated in a separate module
=> feat(ivc): impl `PublicParams::serialize`

src/ivc/public_params.rs, src/nifs/mod.rs, src/nifs/tests.rs, src/nifs/vanilla.rs, src/plonk/mod.rs, src/table.rs
* Remove the commitment calculation for fixed columns, see #85 
* Simplified PlonkStructure
* Added skeleton of folding scheme trait for VanillaFS 
I decided to merge this PR earlier before fully finish the impl of VanillaFS because I found all the PRs that related to PlonkStructure and/or PoseidonHash will require me to do rebase. It's better to merge earlier.
=> refactor(plonk): simplify plonk structure by removing commitment

src/polynomial/mod.rs
This is continuation of previous fix. I realize that by changing the order of the if-else statement, we can make it faster in the case that there are a lot of Monomial term with zero coefficient.
=> fix(expression): improve expression reduction efficiency

src/polynomial/mod.rs
**Motivation**
- Fix bug in expression calculation (ctx in #130 #131)
- Inefficient data structure for cacl the multipolynomial
**Overview**
- Use `BTreeSet` instead of `HashSet` + sort vec after
=> fix(polynomial): expression reduction

examples/sha256/main.rs, src/ivc/incrementally_verifiable_computation.rs, src/ivc/public_params.rs
**Motivation**
In the course of IVC implementation, the public parameters were significantly simplified
**Overview**
- `ck` now provided as referense outside, it allows not to deal with management of such a large object internally and makes the system more flexible
- Only table size instead of `TableData`, each step creates its own `TableData`
- `digest` skips `self.ck`, details at #136
- Instead of general serialization, the transformations needed for hashing became part of the digest method, which is much more correct (as it is not misleading)
=> refactor(ivc): simplify pp

Cargo.toml, src/commitment.rs
Close #132
The methods work directly with memory and simply move it to and from files. Crude, but fast.
**Testing plan**
Unit test with tempdir creation
=> feat(commitment): fast & unsafe work with files

.gitignore, examples/sha256/main.rs, examples/trivial/main.rs
**Motivation**
Creating this file each time is an extremely costly process, the cache allows you to speed up the process
**Overview**
Impl `get_or_create_commitment_key` fn
=> feat(example): add .cache for commitment key

examples/sha256/main.rs, src/gadgets/nonnative/bn/big_uint.rs, src/gadgets/nonnative/bn/big_uint_mul_mod_chip/mod.rs, src/gadgets/nonnative/bn/big_uint_mul_mod_chip/tests.rs, src/ivc/fold_relaxed_plonk_instance_chip.rs
**Motivation**
Some constructors allowed limbs to be less than limbs count limit, which led to errors in on-circuit functions. In addition, the word `limit' was confusing
**Overview**
- Fixed fuzzy number of limbs in `BigUint::from_limbs`
- Rm postfix `_limit` in `limbs_count_limit` everywhere
=> fix(bn): fuzzy number of limbs

examples/sha256/main.rs, examples/trivial/main.rs, src/ivc/incrementally_verifiable_computation.rs, src/ivc/mod.rs, src/ivc/public_params.rs, src/ivc/step_circuit.rs
**Motivation**
For security considerations, we need to commit all gates and parameters inside pp, rather than expecting them to be consistent between steps. For this purpose, we put them back inside PP and put them in digest.
**Overview**
- Now `PublicParams` can create table data by cloning an already prepared version.
- Also these changes required some modification of the step circuit module to get rid of curve there and switch to the field
- Generic for `PublicParams` is certainly a fear, but I'll take the time later to try to simplify it
- The constructor has been augmented with a type because the number of
arguments is too large
=> feat(ivc): `TableData` inside pp

src/plonk/eval.rs, src/polynomial/mod.rs
The optimizations are:
(1) when exponent `k = 0`, skip evaluation of x^k
(2) when first encounter `(x, k)`, cache the values of `x` and `x^k` 
**Benchmark**
Before optimization:
```
Start:   fold_step
··Start:   commit_cross_terms
··End:     commit_cross_terms ......................................................717.736s
··Start:   commit_cross_terms
··End:     commit_cross_terms ......................................................734.656s
End:     fold_step .................................................................1475.241s
```
After optimization:
```
Start:   fold_step
··Start:   commit_cross_terms
··End:     commit_cross_terms ......................................................63.178s
··Start:   commit_cross_terms
··End:     commit_cross_terms …
```
=> feat(eval): optimize MultiPolynomial evaluation 

src/nifs/vanilla.rs, src/plonk/mod.rs, src/poseidon/poseidon_hash.rs, src/poseidon/random_oracle.rs, src/sps.rs, src/table.rs
**Motivation**
- A very common construction we have, when we need to iterate and absorb, it is better to combine them.
- The `chain` absorption design is much more "heap", so much easier to read when you need to aggregate a lot of data in one place
- Consistency with on-circuit random oracle
**Overview**
Fixed the design all over the place
In some places string merging (because return (&mut Self`) can make it confusing that `ro_nark` absorbed the data and then provides it in the same way, so tell me if this seems critical to you as well
=> feat(poseidon): impl `absorb_{point,field}_iter`

src/ivc/incrementally_verifiable_computation.rs, src/plonk/mod.rs
Add `IVC::verify` to check the validity after `n` steps of IVC folding, this is the non zkSNARK version of the decider.
Some of the verifications need to be uncommented after adding `secondary_trace` into the `IVC` structure.
=> feat(Ivc): decider verification of IVC 

src/ivc/step_circuit.rs
Part of #154
To effectively calculate instance off-circuit, you need to be able to calculate `z_out` for an arbitrary step circuit. 
To do this, we make the impl default through running on-circuit calculations, but let the developer implement this method himself in an "honest" way to avoid overheads
- Rename method to `process_step`
=> feat(sp): rn `output` to `process_step` & impl default

src/ivc/fold_relaxed_plonk_instance_chip.rs, src/ivc/incrementally_verifiable_computation.rs, src/ivc/instance_computation.rs, src/ivc/step_folding_circuit.rs, src/poseidon/poseidon_circuit.rs, src/poseidon/poseidon_hash.rs, src/poseidon/random_oracle.rs
During the computation in circuit relaxed plonk instance, the instance & challenge fields were submitted to a set of limbs. Whereas for off-circuit were represented as field elements. This led to non-consistent values X0 & X1
To avoid the extra cost of on-circuit calculations, an off-circuit decomposition of these fields into limbs was added
**Test**
Unit-test for {on,off}-circuit consistency was added
=> fix(icomp): {off,on}-circuit computation of X{0,1}

examples/sha256/main.rs, src/gadgets/nonnative/bn/big_uint_mul_mod_chip/mod.rs, src/gadgets/nonnative/bn/big_uint_mul_mod_chip/tests.rs, src/ivc/fold_relaxed_plonk_instance_chip.rs
After separation of data collections in TableData, the witness data is collected without the need of fixed data collection. This makes some part of the bn chip method error because we cannot rely on the return value of `assign_fixed` method. It will be None. Instead, we directly pass the input of `assign_fixed` instead of return of `assign_fixed`.
Before fix: `m_bn` is assigned as fixed values, then we pass `m_bn` as AssignedCells into other functions. Inside other function call, we just need `m_bn` value from the AssignedCell without copy constraint.
After fix: Pass `m_bn` as BigUint instead of AssignedCell.
=> fix(bn): pass m_bn as value

src/ivc/incrementally_verifiable_computation.rs, src/ivc/instance_computation.rs, src/ivc/step_folding_circuit.rs, src/poseidon/poseidon_circuit.rs, src/poseidon/poseidon_hash.rs, src/poseidon/random_oracle.rs
**Motivation**
One of the main calls for debugging {on,off}-circuit compatibility is to check that the ro inputs are the same. It is convenient to debug this via logs, to make it systematic this method is added.
**Overview**
- change {RO,ROCircuit} traits method `inspect`
- add `generate_with_inspect` methods for instance computation helpers
=> feat(icomp): `generate_with_inspect`

src/ivc/step_folding_circuit.rs
**Motivation**
This is a bug due to the fact that for base-case this check will always fail, becuase that on `instance` the column are always empty on base-case
**Overview**
By `always true` + `conditional_select`
@chaosma please check what I'm using `gate` methods right way - they haven't got docs & I'm not 100% sure
=> fix(ivc): rm input hash check for base-case

examples/sha256/main.rs, examples/trivial/main.rs, src/ivc/incrementally_verifiable_computation.rs, src/ivc/public_params.rs, src/ivc/step_folding_circuit.rs
**Motivation**
In the IVC process, two digests are counted each time step, so it is logical to store them in the cache-fields
Taked from #170 & improved
**Overview**
- store digest into cash-fields with type `OnceCell`
- Since it is now possible that public params can change and their cache not, we add measures to protect against such a scenario by making all fields private. This way no one can change public params & invalidate cash.
=> feat(pp): add cache for pp

src/gadgets/nonnative/bn/big_uint_mul_mod_chip/mod.rs, src/gadgets/nonnative/bn/big_uint_mul_mod_chip/tests.rs
**Motivation**
Fix of bug with fixed limb width for grouped big uint
**Overview**
Add field to structure and use it inside `is_equal`
**WIP**
- Make `limbs-per-group` params of `group_limbs`, because it should be calculated from `max(lhs.max_word, rhs.max_word)`
- Mv grouping into `is_equal`
=> fix(bn): limb width for grouped biguint

src/ivc/fold_relaxed_plonk_instance_chip.rs
**Motivation**
Close #189
**Overview**
Just one `region.next()`
=> fix(ivc): offset for assign witness

examples/sha256/main.rs, examples/trivial/main.rs, src/ivc/incrementally_verifiable_computation.rs
**Motivation**
Our current constraint system used for folding is extremely poor at describing which constraints did not converge. Therefore, when developing and adapting new step-circuits, we will definitely face the problem of debugging. Moreover, both bugs and new features are possible within our folding, which will also require debugging information.
That's why I suggest optional use of `MockProver` within a separate method (with bool flag in main methods). This would not slow down the basic IVC use case, however, such as using it as part of tests.
**Overview**
Just one bool-flag with one separate pub method specially for debug.
=> feat(ivc): `debug_mode`

examples/trivial/main.rs, src/ivc/incrementally_verifiable_computation.rs, src/nifs/tests.rs
Add permutation checks in both `ivc.verify` and `test_nifs`, which is necessary for soundness of the folding scheme.
=> fix(ivc): add permutation check

src/ivc/incrementally_verifiable_computation.rs, src/ivc/public_params.rs, src/ivc/step_folding_circuit.rs, src/nifs/tests.rs
**Motivation**
When creating a circuit we have to take `U` & `u` from another circuit,
not the one being formed, so now there is an error here and the
`without_witness` function is not working as expected
**Overview**
- It's simple to pass the correct generic inside
- cargo-fmt (I didn't understand how the problem got in master, but I fixed it)
=> fix(pp): without witness

Cargo.toml, src/plonk/mod.rs
**Motivation**
These functions were written very much in C, but not in Rust. Let me know if I've gone overboard, however now I at least understand the order of errors and calculations, as well as the error context being conveyed a bit better.
**Overview**
Use `NonZeroUsize` type for mismatch count in errors
An auxiliary `some-to-err` crate is used to shorten the construct
```rust
if let Some(err) = expr {
return Err(err);
}
```
to
```rust
expr.err_or(())?
```
An auxiliary `count-to-non-zero` crate is used to shorten the construct
```rust
let count = iter.count();
if count != 0 {
return Err(Error::Mismatch {
count: NonZeroUsize::new(count).unwrap(),
});
}
```
to
```rust
iter
.count_to_non_zero()
.map(|count| Error::Mismatch { count })
.err_or(())?;
```
```rust
par_iter
.map(|d| func(d)) …
```
=> refactor(plonk): `is_sat` & `is_sat_relaxed`

src/ivc/public_params.rs, src/ivc/step_folding_circuit.rs
**Motivation**
The IVC framework used `StepFoldingCircuit` but the `PublicParams` generation step used only `StepCircuit` itself, this error resulted in a non-consistent PlonkStructure (`S`)
Part of #192 (only one error left at the end)
**Overview**
Corrected the generic. To generate primary use secondary and vice versa
=> fix(pp): using sfc instead of sc for pre-config

src/ivc/incrementally_verifiable_computation.rs, src/ivc/public_params.rs, src/ivc/step_folding_circuit.rs
**Motivation**
Our initial plonk trace was incorrect and poisoned the entire relaxed trace for the secondary circuit.
Close #192
**Overview**
Now when creating public parameters, we not only calculate `S` (`PlonkStructure`), but also calculate the correct trace for the secondary input to use as the initial trace
The fact that the trace is computed on incorrect `u` & `U` (null traces do not converge) is immaterial, since internal traces are not used, only their folding traces are used.
=> fix(ivc): correct init secondary trace

src/util.rs
There is a typo in the halo2 prover which need to be changed.
=> fix(util.rs): fix typo in halo2 prover

Cargo.toml, examples/sha256/table16/compression.rs, examples/sha256/table16/message_schedule.rs, examples/sha256/table16/mod.rs, examples/sha256/table16/spread_table.rs, src/commitment.rs, src/digest.rs, src/gadgets/ecc.rs, src/gadgets/nonnative/bn/big_uint.rs, src/gadgets/nonnative/bn/big_uint_mul_mod_chip/tests.rs, src/ivc/fold_relaxed_plonk_instance_chip.rs, src/ivc/instance_computation.rs, src/ivc/public_params.rs, src/main_gate.rs, src/nifs/tests.rs, src/polynomial/expression.rs, src/poseidon/poseidon_circuit.rs, src/poseidon/poseidon_hash.rs, src/poseidon/spec.rs, src/table/tests.rs, src/util.rs
**Motivation**
After migration to 'tracing' we should use `tracing_test` for see logs in tests run
**Overview**
- Automatically added `traced_test` to all tests in the project
=> fix: use 'tracing_test' instead of 'test_log'

src/polynomial/grouped_poly.rs
**Motivation**
The degree is small, so HashMap is redundant here
Part of #159 
**Overview**
Simple enough migration. Also corrected an error in subtraction with this implementation. It is possible to use `vec_option` crate to optimise storage of discriminators, but I will try to use it when there is a benchmark
=> feat(159): `HashMap<usize, _>` -> `Vec<Option<_>>`

src/polynomial/expression.rs
**Motivation**
Look at https://github.com/snarkify/sirius/issues/159#issuecomment-2038794079
**Overview**
Final form homogeneous expression is not as obviously readable as the version that came before, but I think this is not such a big problem, since the original type is preserved
I also added a return struct for:
- tracking degree during a recursive call
- tracking the fact that the given `Expression` is already homogeneous, in some places we can use this wrapper as a guarantee (e.g. add it to `GroupedPoly`).
=> feat(poly): impl `Expression::homogeneous`

.github/workflows/rust.yml
**Motivation**
CI tests are slow, to speed things up a bit it would be good to get information on specific tests and also speed things up a bit
**Overview**
- I use the cargo-nextest plugin, to run tests, it will provide more information in Action
- from 12m to 4m with `cargo test --release`
=> ci: migrate to cargo-nextest & release in tests

src/digest.rs, src/ivc/public_params.rs, src/plonk/mod.rs, src/polynomial/expression.rs, src/polynomial/grouped_poly.rs, src/polynomial/mod.rs, src/table/constraint_system_metainfo.rs
**Motivation**
To understand which `Expression` is the `Advice` or `Lookup`
representation of a column and which is any other type (Selector, Fixed)
we have to flip the whole context to calculate the relative index and
define the `Polynomial` subtype. We need to move towards making these
rules localized in the code and not requiring to remember them while
working with indexes
Part of #159 
**Overview**
- Introduced a new type that defines all `num_of`
- Subtype `QueryType` introduced
- The `Expression::homogeneous` function no longer uses `evaluate`, due to the overhead of using closure
- Lookup polynomials are now taken into account in `Expression::homogeneous` function
- Removed recursion for calculating `Challenge` in degree within `homogeneous` fn
- Removed an unnecessary `clone` call …
=> feat(poly): impl `QueryIndexContext`

Cargo.toml, benches/poseidon/main.rs, benches/trivial/main.rs, examples/poseidon/main.rs, examples/sha256/main.rs, src/commitment.rs
**Motivation**
I'd like to have an easy way to check how a particular code change affects performance, as well as have reports on averages between runs. 
Such a solution would allow us to track the impact of certain features quite easily. 
Close #33 & MPV milestone 
**Overview**
I just moved the example inside the benches and added a 'criterion' crate (actually the default solution in the Rust ecosystem). The only downside is that due to the huge bench `IVC::fold` we can only run 10 samples, but the spread between runs is very small, so it's not critical.
Let me know if you need more info on cargo-criterion and how to use it, but I was planning to add it to the README under #247 anyway
```
cargo install cargo-criterion; cargo criterion
```
This command allows you to create a full-fledged …
=> feat(example): upd examples & add benches

src/fft.rs, src/lib.rs
close #258 
In protogalaxy, there are several places need fft/ifft, e.g. when prover wants to compute F, G and K
* root of unity generation for a given fft domain size.
* fft and ifft function. The `fn best_fft` is imported from halo2curves.
* unit test for random inputs
=> feat(fft): add fft/ifft

.cargo/config.toml, Cargo.toml, README.md, examples/cli.rs, examples/poseidon.rs
**Motivation**
Now we have a default path for time-profling & mem-profiling, but it is not very convenient to vary the runtime parameters by hand. That's why I put all runtime parameters in a separate cli example. This allows us to do time-profiling & mem-profiling on different parameters directly on the command line
Part of #272 
**Overview**
Fairly simple code that parses parameters with clap and runs circuit. Covers all our examples
Once mem-profiling is in main, I'll add its description to the README along with this example
```console
Usage: cli [OPTIONS] [PRIMARY_CIRCUIT] [SECONDARY_CIRCUIT]
Arguments:
[PRIMARY_CIRCUIT]    [default: poseidon] [possible values: poseidon, trivial]
[SECONDARY_CIRCUIT]  [default: trivial] [possible values: poseidon, trivial]
Options: …
```
=> feat(example): cli

src/nifs/vanilla.rs, src/plonk/eval.rs, src/plonk/mod.rs
**Motivation**
- The antipattern of taking `&Vec` was used. `&[_]` is a more generalized type
- Some fields were copied unnecessarily
Implemented as part of #259
**Overview**
N/A
=> refactor(plonk): `&Vec<_> -> &[_]` in `PlonkEvalDomain`

src/ivc/public_params.rs
Close #136 
skip serialization of commitment keys.
With table size `k=17` and commitment key of size `2^27`, i.e. each key has 8GB size.
**time profile**
before
```
··Start:  pp_new
····Start:  primary
······Start:  circuit_collect_plonk_struct
······End:    circuit_collect_plonk_struct.................................0.38s
····End:    primary........................................................0.38s
····Start:  secondary
······Start:  process_step
······End:    process_step.................................................0.00s
······Start:  circuit_collect_plonk_struct
······End:    circuit_collect_plonk_struct.................................0.24s
······Start:  circuit_collect_witness
······End: …
```
=> perf(pp): skip serialization and digest of commitment key

benches/poseidon/main.rs, benches/trivial/main.rs, examples/cli.rs, examples/poseidon.rs, examples/sha256/main.rs, examples/trivial/main.rs, src/ivc/incrementally_verifiable_computation.rs
**Motivation**
Our API should allow step-circuit to be changed between rounds of folding. As part of #285, we will change the private input (merkle-tree leaves changing) at each iteration of folding
**Overview**
It's just that now IVC is taking the step circuit from the ref
=> refactor(ivc): take out step-circuit's ownership

.cargo/config.toml, Cargo.toml, examples/cli.rs, examples/merkle/circuit.rs, examples/merkle/main.rs, examples/merkle/mod.rs
**Motivation**
For easier and faster benchmarking, cli should be improved and merkle-tree circuit should be added there
**Overview**
- added possibility to select any combination of circuits to start within cli
- for merkle added possibility to change circuits in intervals between fold_step
NOTE: there is a nasty big match inside that can be simplified with macros, I'll allocate an issue for that later
=> feat(example): add merkle-tree to cli

Cargo.toml, examples/cli.rs, examples/merkle/kzg.rs, examples/merkle/main.rs
**Motivation**
In all scripts, I redirect logs to files where the file name is the defining file for the run case. To simplify the startup scripts of different scripts I added file creation at the Rust code level
**Overview**
- Made a flag to redirect output to a file
- Used git2 crate to find git-workdir when running from any repository directory
- Made for cli & merkle
=> feat(example): arg to write logs into file

src/nifs/protogalaxy/mod.rs, src/nifs/protogalaxy/poly/mod.rs, src/nifs/vanilla.rs, src/plonk/mod.rs
**Motivation**
Since we already have a type that represents this tuple, we can use it
Part of #266
**Overview**
Just change return type in API
=> refactor(nifs): use `PlonkTrace` in sps protocol

src/ivc/incrementally_verifiable_computation.rs, src/ivc/public_params.rs, src/nifs/mod.rs, src/nifs/protogalaxy/mod.rs, src/nifs/tests.rs, src/nifs/vanilla.rs
**Motivation**
The errors will be different for vanila & protogalaxy, so a slightly different design of `trait FoldingScheme` methods is needed Part of #266
**Overview**
Old generic error type moved to `nifs::vanila` module
=> refactor(nifs): err in `nifs::FoldingScheme`

src/ivc/incrementally_verifiable_computation.rs, src/nifs/mod.rs, src/nifs/protogalaxy/accumulator.rs, src/nifs/protogalaxy/mod.rs, src/nifs/protogalaxy/poly/folded_trace.rs, src/nifs/protogalaxy/poly/mod.rs, src/nifs/tests.rs, src/nifs/vanilla.rs, src/plonk/mod.rs, src/polynomial/univariate.rs
**Motivation**
Part of #266
**Overview**
Implement `Protogalaxy::prove`
**Note**
Since the tests involve refactoring existing code to test Vanilla (circuit reuse), I'll separate them into a separate PR
=> feat(nifs): impl `Protogalaxy::prove`

src/nifs/mod.rs, src/nifs/tests.rs, src/nifs/vanilla/mod.rs, src/nifs/vanilla/tests.rs
**Motivation**
In #266 we need to test the protogalaxy folding scheme, for this I want to reuse circuits from `nifs::vanila` tests
**Overview**
- Move test-circuits to `nifs::tests` module
- Move current tests of vanilla to `nifs::vanilla::tests`, instead of `nifs::tests`
- This PR does not add any new code
=> refactor(nifs): tests of nifs

Cargo.toml, rust-toolchain.toml, src/ivc/step_circuit.rs
**Motivation**
As part of https://github.com/snarkify/sirius/milestone/4
**Overview**
Make less strict deps of some crates & impl `From<Halo2Error>` for `sirius::SynthesisError~
=> fix: compatibility with zkevm

src/ivc/fold_relaxed_plonk_instance_chip.rs, src/ivc/incrementally_verifiable_computation.rs, src/ivc/instance_computation.rs, src/ivc/step_folding_circuit.rs, src/nifs/protogalaxy/accumulator.rs, src/nifs/protogalaxy/mod.rs, src/nifs/vanilla/accumulator.rs, src/nifs/vanilla/mod.rs, src/nifs/vanilla/tests.rs, src/plonk/mod.rs
**Motivation**
After the introduction of new types `FoldingScheme` `Relaxed*` structures turned out to be just one of the subtypes of accumulators and to keep their fields out of the way, they were moved to a separate structure
**Overview**
No new code was introduced as part of this PR, just moved the strings and renamed the `to_relax` -> `from_regular` methods
=> refactor(nifs): mv `Relaxed*` into 'nifs::vanilla'

Cargo.toml
**Motivation**
To use the version tag in the documentation
**Overview**
Once the PR is merged, I'll also git-tag to commit in master it and that will allow to add a project depending on the tag, which is the most idiotmatic way to add project to deps
Like:
```
cargo add --git https://github.com/snarkify/sirius/ --tag v0.1.1;
```
=> chore: bump version to v0.1.1

examples/my_circuit.rs, src/commitment.rs, src/ivc/step_circuit.rs, src/lib.rs, src/nifs/protogalaxy/tests.rs, src/nifs/tests.rs, src/nifs/vanilla/tests.rs
**Motivation**
As part of #330 task, documentation is needed, so we need to simplify the API and put all the entrainment values in some module (prelude) so that the developer can focus on development
**Overview**
- Added `sirius::prelude` & `sirius::prelude::bn256` module.
- Refactored `get_smallest_commitment_key` fn
- Trivial example was simplified
- Added `MyCircuit` example
- Pub re-import for step-circuit module
Basically check out trivial-example to see if I've taken out anything too critical
It seems to me that the same `T` (which we have for both poseidon and step-folding-circuit size) is not understood by the developer, so we can take it as default and simplify the public API
=> refactor: simplify trivial example

src/fft.rs, src/nifs/protogalaxy/poly/mod.rs
**Motivation**
In this case the parameter is derived from another parameter and their equality is checked, to avoid an error it is better not to do it this way
**Overview**
- rm `log_n: u32` from fft/ifft
- add tests for `bitreverse`
=> refactor(fft): rm `fft_domain_size` from args

src/polynomial/univariate.rs
**Motivation**
In testing #267, basic operations on `UnivariatePoly` were needed
**Overview**
- impl `Add`
- impl `Mul`
- impl `degree`
- impl `into_iter`
- impl `resize`
- impl `len` & `is_empty`
- impl `scale`
- impl `fft` & `ifft` proxy
=> feat(poly): add functionality to `univariate` mod

src/nifs/protogalaxy/accumulator.rs, src/nifs/protogalaxy/mod.rs, src/nifs/protogalaxy/poly/folded_witness.rs, src/nifs/protogalaxy/poly/mod.rs, src/nifs/protogalaxy/tests.rs, src/polynomial/lagrange.rs
**Motivation**
Within the protogalaxy implementation we count many intermediate constants, we need SSOT to count in one place and easily verifiable
Part of #267
**Overview**
- impl `AccumulatorInstance::into_acc`
- impl `poly::PolyContext` struct
- refactor `FoldedTrace` -> `FoldedWitness`
- fix in `FoldedWitness` -> use correct `lagrange_domain`
- refactor `compute_K` for better testing
=> fix(nifs): impl `PolyContext` for protogalaxy

src/ivc/consistency_marker_computation.rs, src/ivc/consistency_markers_computation.rs, src/ivc/fold_relaxed_plonk_instance_chip.rs, src/ivc/incrementally_verifiable_computation.rs, src/ivc/mod.rs, src/ivc/public_params.rs, src/ivc/step_folding_circuit.rs, src/nifs/vanilla/mod.rs, src/plonk/mod.rs
**Motivation**
Since thanks to #316 we support as many instance columns as we like, the old name can be misleading, so wherever possible we enter the name "consistency marker", including this module
**Overview**
N/A
=> refactor(ivc): use `ConsistencyMarkersComputation` name

src/ivc/consistency_markers_computation.rs, src/ivc/fold_relaxed_plonk_instance_chip.rs, src/ivc/step_folding_circuit.rs, src/nifs/protogalaxy/tests.rs, src/nifs/tests.rs, src/nifs/vanilla/accumulator.rs, src/nifs/vanilla/mod.rs, src/nifs/vanilla/tests.rs
Part of #316
First, we need to remove the nested format `RelaxedPlonkInstance` and add the accumulator field for the rest of the instances in the following PR
- **Removed `inner` field** from `RelaxedPlonkInstance`.
- **Directly embedded fields**: `W_commitments`, `consistency_markers`, and
`challenges`.
- **Introduced `try_new` and `try_from` methods** for creating
`RelaxedPlonkInstance`.
- **Updated test cases** to align with the new structure.
=> refactor(nifs): rm instances from `RelaxedPlonkInstance`

src/ivc/consistency_markers_computation.rs, src/ivc/fold_relaxed_plonk_instance_chip.rs, src/ivc/incrementally_verifiable_computation.rs, src/ivc/instances_accumulator_computation.rs, src/nifs/vanilla/accumulator.rs, src/nifs/vanilla/mod.rs
**Motivation**
Practically complete realization of task #316
**Overview**
Impl of accumulation of step circuit instances
- Addition of a `step_circuit_instances_hash_accumulator` to the `RelaxedPlonkInstance` structure.
- Implementation of methods to fold and conditionally select step circuit instances.
- Modification of existing methods to incorporate the new accumulator.
- Update to testing modules to cover the changes.
=> feat(ivc): accumulation of step circuit instances

src/ivc/consistency_markers_computation.rs, src/ivc/fold_relaxed_plonk_instance_chip.rs, src/ivc/incrementally_verifiable_computation.rs, src/ivc/instances_accumulator_computation.rs, src/ivc/mod.rs, src/nifs/vanilla/accumulator.rs, src/nifs/vanilla/mod.rs
**Motivation**
As part of #316, we need to accumulate `instance`, using a poseidon hash. This PR should provide a consistent way to do this {on,off}-circuit within nifs::vanilla
**Overview**
- New Module
- Added `instances_accumulator_computation.rs` to handle the accumulation of `instances` using the Poseidon hash function.
- Functions:
- `fold_step_circuit_instances_hash_accumulator` for off-circuit hash accumulation.
- `fold_assign_step_circuit_instances_hash_accumulator` for on-circuit hash accumulation
- Testing:
- Added comprehensive unit tests to verify the consistency of the accumulator computation.
=> feat(ivc): impl `instances_accumulator_computation`

src/gadgets/util.rs
**Motivation**
There was a bug, since:
- `a` was twice assigned into s[0] rather than into s[0] & s[1]
- `q_o` was not assigned at all, but `q_m` was assigned twice.
So the actual check did not take place
**Overview**
Aside from the fix itself, I've refactored a bit to make it more obvious
which columns are used within the function
=> fix(gadgets): bugs in assign_bit

examples/instances.rs, src/ivc/consistency_markers_computation.rs, src/ivc/fold_relaxed_plonk_instance_chip.rs, src/ivc/incrementally_verifiable_computation.rs, src/ivc/instances_accumulator_computation.rs, src/ivc/mod.rs, src/nifs/protogalaxy/mod.rs, src/nifs/vanilla/accumulator.rs, src/nifs/vanilla/mod.rs, src/plonk/mod.rs, src/plonk/permutation.rs, src/plonk/util.rs, src/table/circuit_runner.rs
**Motivation**
As part of #316, we will need to remove some copy constraints before checking for correctness. To achieve this, I saved the information needed to build the matrix and built it on demand.
Next PR will add copy constraint cutout
**Overview**
This PR refactors the `PlonkStructure` by introducing the `PermutationData` struct to manage permutation matrix data. It replaces direct usage of `SparseMatrix` with a method to construct the permutation matrix on demand.
=> refactor(nifs): remaster permutation in `PlonkStructure`

src/ivc/fold_relaxed_plonk_instance_chip.rs, src/ivc/incrementally_verifiable_computation.rs, src/ivc/instances_accumulator_computation.rs, src/ivc/public_params.rs, src/ivc/step_folding_circuit.rs, src/nifs/mod.rs, src/nifs/protogalaxy/mod.rs, src/nifs/vanilla/accumulator.rs, src/nifs/vanilla/mod.rs, src/nifs/vanilla/tests.rs
**Motivation**
During the implementation of #316 we added a condition that consistency tokens started to be collapsed differently than all other instances, which in fact added a constraint to `nifs::FS` that now only traces with two elements in the first instance column can be collapsed. Otherwise, the behavior is undefined. This PR solves the problem of checking this restriction
**Overview**
The newtype pattern was used to solve the problem in this way. An example of using such a pattern is the `NonZero<T>` wrapper from the standard library. Now, instead of checking in all functions that involve consistency tokens, we accept `vanilla::FoldablePlonkTrace` instead of `PlonkTrace`. This type can only be created with a single constructor, which performs the trace validity check at the point …
=> feat(nifs): `Foldable` wrapper for trace

src/plonk/permutation.rs, src/table/circuit_runner.rs
**Motivation**
Part #316
The previous algorithm was not accurate, it was losing links to the columns being deleted
**Overview**
- Now the columns are sorted even before copy-constraint is added to avoid any double-pointing
- Added unit-tests
=> fix(plonk): algo for permutation

src/gadgets/ecc.rs, src/ivc/consistency_markers_computation.rs, src/ivc/instances_accumulator_computation.rs, src/ivc/public_params.rs, src/ivc/sangria/fold_relaxed_plonk_instance_chip.rs, src/ivc/sangria/incrementally_verifiable_computation.rs, src/nifs/protogalaxy/accumulator.rs, src/nifs/protogalaxy/mod.rs, src/nifs/sangria/accumulator.rs, src/plonk/mod.rs, src/sps.rs, src/util/mod.rs
**Motivation**
We have a lot of distillations between base -> scalar. Perhaps within a cyclefold implementation this transformation would be optional, as there would be no curve cycle
**Overview**
For now, I've just labeled all these places through a separate API - `trait BaseToScalar: CurveAffine`. Also, if we have to support more curve, we can make this conversion between curves safer
No functional changes have been made
=> refactor(util): `ScalarToBase` + `BaseToScalar`

src/ivc/mod.rs, src/ivc/protogalaxy/mod.rs, src/nifs/protogalaxy/accumulator.rs, src/nifs/protogalaxy/mod.rs
**Motivation**
First part of #361
**Overview**
Implemented `ivc::protogalaxy::verify_chip` module blank and signature of the verification fn, together with assignment logic
=> feat(ivc): impl protogalaxy verify circuit mod-blank

src/ivc/protogalaxy/mod.rs, src/nifs/protogalaxy/mod.rs, src/nifs/protogalaxy/tests.rs, src/polynomial/univariate.rs, src/poseidon/poseidon_circuit.rs, src/poseidon/poseidon_hash.rs, src/poseidon/random_oracle.rs
**Motivation**
Part of #361
**Overview**
- Implementation of the same generation challanges as in `nifs::protogalaxy` mod
- Consistency test added for challenges generation at {on,off}-circuit env
- Corrected the number of bits generated for challenges (`MAX_BITS` will now be used)
**Fix poseidon off-circuit hash**
Previously, a successive on-circuit poseidon circuit call would cause the old buffer to be reused and the exact same successive off-circuit call would not reuse the previous buffer. Now the behavior has been brought to a uniform standard.
=> feat(ivc): generate assigned challanges

src/ivc/protogalaxy/mod.rs, src/nifs/protogalaxy/poly/mod.rs
**Motivation**
Part of protogalaxy protocol in #361
**Overview**
Implemented a separate function to get similar `nifs::protogalaxy` beta_stroke calculations
=> feat(ivc): impl `protogalaxy::calculate_betas_stroke`

src/ivc/protogalaxy/mod.rs, src/polynomial/univariate.rs
**Motivaion**
To compute `e` in the framework of #361, we need to be able to compute proof.poly_{F,K} for the on-circuit version
**Overview**
- Due to the two multiplications within `main_gate`, the polynomial calculation was split into chunks=2
- Since powers of the same values powers will be used in multiple places, its computation has been delegated to a separate struct. This calculation can be optimized (again due to the two multiplications, but it is simpler for speed).
- In other tests in ivc::protogalaxy module we test only on-circuit calculations, since ready-made gadgets are used, here we test everything, including correctness of constraint system
=> feat(ivc): `protogalaxy::AssignedUnivariatePoly::eval`

src/gadgets/util.rs, src/ivc/protogalaxy/mod.rs, src/nifs/protogalaxy/mod.rs
**Motivation**
As part of #361 we calculate `L0(gamma)`
**Overview**
Simple implementation without optimizations, using ready operations from main_gate
=> feat(ivc): impl `eval_lagrange_poly_zero`

src/ivc/protogalaxy/mod.rs, src/nifs/protogalaxy/accumulator.rs, src/nifs/protogalaxy/mod.rs, src/nifs/protogalaxy/tests.rs
**Motivation**
Last part of #361
**Overview**
Unlike the rest of the functionality, this one is untested because the test would need a cyclic curve and that makes the tests very difficult.
It is better to test this part of e2e already
=> feat(ivc): impl `protogalaxy::fold_instances`

src/ivc/protogalaxy/mod.rs, src/nifs/protogalaxy/accumulator.rs, src/nifs/protogalaxy/mod.rs, src/nifs/protogalaxy/tests.rs
**Motivation**
Close #367
**Overview**
Tests for this functionality will be done within a more upper-level module to simplify the mocks
=> feat(ivc): impl `protogalaxy::verify_sps`

examples/sha256/table16/compression/compression_gates.rs, rust-toolchain.toml, src/ivc/consistency_markers_computation.rs, src/ivc/cyclefold/sfc/mod.rs, src/ivc/protogalaxy/mod.rs, src/ivc/public_params.rs, src/ivc/sangria/step_folding_circuit.rs, src/util/mock_prover.rs, src/util/mod.rs
**Motivation**
Within #369 and cyclfold in general we need to count consistency markers, for this we need to be able to absorb sfc::input
**Overview**
Just implementation of `AbsorbInRO` trait for all sfc::input types
=> feat(ivc): cyclefold::sfc ro_absorb

src/ivc/cyclefold/incrementally_verifiable_computation/public_params.rs, src/ivc/cyclefold/mod.rs, src/ivc/cyclefold/sfc/input/assigned.rs, src/ivc/cyclefold/sfc/input/mod.rs, src/ivc/cyclefold/sfc/mod.rs, src/nifs/protogalaxy/mod.rs
**Motivaion**
As part of #369 we need impl assigned version of input. Also we have to make sure that {on,off}-circuit assigned works the same way to match the consistency marker
**Overview**
Implemented versions of Input structures. A test to check the consistency of the {on,off}-circuit hash has been implemented. Also this test allows to double-check correctness of assignment
=> feat(ivc): impl cyclefold::sfc::input::assigned

src/gadgets/ecc/point.rs, src/ivc/cyclefold/incrementally_verifiable_computation/public_params.rs, src/ivc/cyclefold/mod.rs, src/ivc/cyclefold/sfc/input/assigned.rs, src/ivc/cyclefold/sfc/input/mod.rs, src/ivc/cyclefold/sfc/mod.rs, src/ivc/cyclefold/sfc/sangria_adapter.rs, src/ivc/sangria/fold_relaxed_plonk_instance_chip.rs
**Motivation**
In #369 we have to fold the paired circuit with sangria
**Overview**
I've reused almost all fold-fn (except `instance`) from the existing sangria implementation
Tests will be in the next PRs
=> feat(ivc): impl sangria::verify in cyclefold

src/gadgets/ecc/mod.rs, src/gadgets/util.rs, src/ivc/cyclefold/sfc/input/assigned.rs, src/ivc/cyclefold/sfc/mod.rs, src/ivc/cyclefold/support_circuit/mod.rs, src/ivc/protogalaxy/mod.rs
**Motivation**
We need to have consistency checks between steps for sfc under #369
**Overview**
The input is checked via access to `self_trace.incoming` The output is checked via constraint system at the current step
Only pairing connection & tests for sfc left in #369
=> feat(ivc): `cyclefold::consistency_marker`

src/ivc/consistency_markers_computation.rs, src/ivc/cyclefold/sfc/sangria_adapter.rs, src/ivc/cyclefold/support_circuit/mod.rs, src/ivc/public_params.rs, src/ivc/sangria/fold_relaxed_plonk_instance_chip.rs, src/ivc/sangria/incrementally_verifiable_computation.rs, src/ivc/sangria/step_folding_circuit.rs, src/nifs/protogalaxy/accumulator.rs, src/nifs/protogalaxy/mod.rs, src/nifs/sangria/accumulator.rs, src/nifs/sangria/mod.rs, src/nifs/sangria/tests.rs
**Motivation**
For cyclefold (#369) we must use the number of markers (first column) equal to nine, not two, to insert the data we need there (W_commitments)
**Overview**
We add the `MARKER_LEN` generic parameter wherever it is needed to use the sangria protocol
=> feat(ivc): sangria consistency markers len

src/gadgets/ecc/mod.rs, src/ivc/sangria/fold_relaxed_plonk_instance_chip.rs
**Motivation**
During implementation #373, it was discovered that the ecc gadget does not work correctly when multiplying zero points
The point is that unsafe methods were called that were unsafe for some inputs, but it was implied that their result was not used in case of a match. However, this led to incorrect witness (verification errors), because the logic should be the opposite - the verification should go before the call.
**Overview**
- Nonnull checks are performed BEFORE unsafe blocks are called
- Added tests
- For tests with ecc `K_TABLE_SIZE` was increased, because additional lines for non-zero checks
=> fix(gadgets): additional unsafe checks

src/ivc/cyclefold/incrementally_verifiable_computation/public_params.rs, src/ivc/cyclefold/mod.rs, src/ivc/cyclefold/sfc/input/assigned.rs, src/ivc/cyclefold/sfc/input/mod.rs, src/ivc/cyclefold/sfc/sangria_adapter.rs, src/ivc/protogalaxy/mod.rs, src/nifs/protogalaxy/accumulator.rs, src/nifs/protogalaxy/mod.rs, src/nifs/protogalaxy/poly/mod.rs, src/nifs/protogalaxy/tests.rs
**Motivation**
ProtoGalaxy accumulator was created immediately by `!is_sat`, which prevents folding in #373
**Overview**
- The protogalaxy accumulator logic has been changed
- AssignedBigUint within ivc::protogalaxy is now an array. This generated a certain number of try_into().unwrap(), however, these will be cleaned up soon
- Changed the order of absorption in ro, for consistency with cyclefold
=> fix(nifs): protogalaxy initial acc

src/ivc/cyclefold/sfc/input/assigned.rs, src/ivc/cyclefold/sfc/input/mod.rs, src/ivc/cyclefold/sfc/mod.rs, src/ivc/cyclefold/sfc/sangria_adapter.rs
**Motivation**
This PR combines all the changes for operability #373
**Overview**
- Renamed `PairedPlonkInstance` and `PairedTrace` to `SupportPlonkInstance` and `SupportTrace` for better alignment with the functionality
- Added alignment for W_commitments & challenes, since we don't know them at the "before zero step" stage, this takes 300 extra rows
- Changed `Input` absorption order for consistency from nifs::{sangria,protogalaxy} (Some fields are now converted to bn, oncircuit only)
=> feat(ivc): impl `cyclefold::sfc`

src/gadgets/ecc/mod.rs, src/ivc/sangria/step_folding_circuit.rs, src/nifs/protogalaxy/mod.rs, src/nifs/protogalaxy/poly/mod.rs, src/plonk/mod.rs, src/table/constraint_system_metainfo.rs
**Motivation**
As part of the sha256 testing, some bottle necks and bugs were discovered for a large number of gates
**Overview**
- Added alignment when creating a new gate
- Parallelized process of finding source `protogalaxy_acc.e`
- Added alignment when calculating `protogalaxy_acc.e`
- Fixed wrong boundary in witness calculation
- Counting `grouped gates`, only as required
```terminal
cyclefold_ivc_of_poseidon/fold_1_step                                                                          3
time:   [19.804 s 19.982 s 20.140 s]
change: [-11.874% -10.841% -9.9128%] (p = 0.00 < 0.10)
Performance has improved.
```
=> perf(nifs): protogalaxy::nifs
