- src/plonk/lookup.rs
* move table vector from witness to structure
* remove g_mat/h_mat
> quick fix on lookup structure

- src/gadgets/nonnative/bn/big_uint.rs
- src/gadgets/nonnative/bn/big_uint_mul_mod_chip/mod.rs
- src/gadgets/nonnative/bn/big_uint_mul_mod_chip/tests.rs
- src/main_gate.rs
Impl fn with proof of decomposition one assigned cell into limbs
Close https://github.com/snarkify/sirius/issues/48
> feat(bn): impl `from_assigned_cell_to_limbs`

- examples/sha256/main.rs
- src/gadgets/ecc.rs
- src/ivc/fold_relaxed_plonk_instance_chip.rs
- src/ivc/incrementally_verifiable_computation.rs
- src/ivc/mod.rs
- src/ivc/step_circuit.rs
- src/main_gate.rs
> feat(ivc): fold of relaxed plonk instance

- src/ivc/fold_relaxed_plonk_instance_chip.rs
- src/nifs.rs
- src/plonk/lookup.rs
- src/plonk/mod.rs
- src/poseidon/mod.rs
- src/poseidon/poseidon_hash.rs
- src/util.rs
* finished sps_protocol for all cases
* add sps_verifier for PlonkInstance
* use create_ro to create random oracles in fold_instance
> special soundness protocol for lookup (part 2)

- src/gadgets/nonnative/bn/big_uint_mul_mod_chip/mod.rs
- src/gadgets/nonnative/bn/big_uint_mul_mod_chip/tests.rs
> feat(bn): impl `to_le_bits`

- src/nifs/tests.rs
It is important that test case are easy to read, because then they are much easier to use, maintain and extend by adding for example new test cases.
So I spent some time refactoring, making the calculation of each `TableData` compact, so that the whole chain (input, output, circuit) can be easily traced.
Also sequences are commonly done via iterators because of the convenient lazy logic, so I added them. This NBD, however, improves the flexibility of the code.
> refactor(nifs): concise test cases

- src/main_gate.rs
For some cases we just need to `assign` data to tables without using constraint system capabilities, e.g. for IVC input. For this purpose, it is convenient to take a expr that simply gives all available columns and does a row shift when the columns run out:
Now we need the following code for cyclic assign:
```rust
let mut fixed_columns = config.iter_fixed_columns().enumerate().cycle();
// A closure using a cyclic iterator that allows you to take available advice columns
// regardless of `T`, making as few row offsets as possible
let mut assign_next_fixed =
move |annotation: &str, region: &mut RegionCtx<C::Base>, val| {
let (index, column) = fixed_columns.by_ref().next().expect("Safe because cycle");
if index == 0 {
region.next();
}
region.assign_fixed(|| annotation.to_owned(), *column, …
```
> feat(mg): impl cyclic assigner

- src/ivc/fold_relaxed_plonk_instance_chip.rs
- src/util.rs
Docs & test & logs for fold_instances
Part of https://github.com/snarkify/sirius/issues/32
_Accidentally merged #98, so I'm resuming PR and need to remove the ability to merge without Approve to avoid this happening_
> test(ivc): impl `fold_instances_test`

- src/ivc/fold_relaxed_plonk_instance_chip.rs
For fold challenges
Part of https://github.com/snarkify/sirius/issues/32
> test(ivc): impl `fold_challenges_test`

- src/nifs/mod.rs
Because:
- DRY
- This fn is needed in test of IVC
> refactor(nifs): separate `generate_challenge`

- src/ivc/fold_relaxed_plonk_instance_chip.rs
**Before**
```rust
let m_bn = BigUint::<C::Base>::from_biguint(
&num_bigint::BigUint::from_str_radix(
<C::Scalar as PrimeField>::MODULUS.trim_start_matches("0x"),
16,
)
.unwrap(),
self.limb_width,
self.limbs_count,
)?
.limbs()
.iter()
```
**After**
```rust
let m_bn = scalar_module_as_limbs::<C>(self.limb_width, self.limbs_count)?
.iter()
```
> refactor(ivc): impl `scalar_module_as_limbs`

- src/ivc/fold_relaxed_plonk_instance_chip.rs
- src/ivc/step_circuit.rs
For base case of ivc we just need to make assignment of a certain relaxed plonk instance, so a corresponding method has been added.
Since there is another method that allows you to make assignments, auxiliary functions were added that allow you not to violate DRY when assigning values to arbitrary advice columns.
---
@chaosma please check [full code](https://github.com/snarkify/sirius/blob/d38ff68856b1328171dbd5671ea3fdd2a0f49e8f/src/ivc/step_circuit.rs#L215-L249) of `StepCircuitExt::synthesize_step_base_case`
Part of #32
> feat(ivc): impl `ext::synthesize_step_base_case`

- src/gadgets/util.rs
- src/ivc/step_circuit.rs
This PR implements input data preparation and the `StepCircuit::synthetize_step` call
For a complete implementation of `StepCircuitExt` all that is left is to call RandomOracle at the end on all data and pass on assigned values as result of `StepCircuitExt::synthesize`
Part of #32
> feat(ivc): integrate `StepCircuit::synthetize_step`

- src/poseidon/mod.rs
**Why?**
Within IVC we have to use `ROCircuitTrait` & `R0Trait`, I suggest we link them using associated type so that we have `OffCircuit` & `OnCircuit` version of random oracle. This will simplify generics by an order of magnitude.
**What?**
Adding a new trait `ROPair`
**How?**
We add a new trait and link two types of random oracle there. With generics we make it so that they can be created from the same argument. In our case (poseidon) it is a specification.
> feat(poseidon): link off-circuit & on-circuit

- src/util.rs
As part of the IVC implementation, faced the need to work with huge vectors, and here is an opportunity to speed this up via rayon
The function does the same thing, just adding rayon internally, using a paralel iterator
**Testing plan**
Added missing function unit tests
> feat(util): make parallel `concatenate_with_padding`

- examples/trivial/main.rs
**Motivation**
For debugging, we need something faster than sha256
**Overview**
Two trivial step circuits are being folded
> feat(example): add 'trivial' example

- src/ivc/fold_relaxed_plonk_instance_chip.rs
- src/main_gate.rs
**Motivation**
Simplify a repetitive construct when we need to iterate some collection.
**Overview**
Adding a new simple method for fixed&advice columns
> feat(mg): convenient assignor for iterators

- src/plonk/lookup.rs
- src/util.rs
**Motivation**
In a real example of IVC's work, the process was literally freezing up
**Overview**
- Removed quadratic complexity in m calculation
- Added paralellization where possible
> feat(plonk): better perf for lookup fold

- src/nifs/vanilla.rs
**Motivation**
Close #147
**Overview**
Based on information from #147 explain both of random oracles in nifs protocol
> docs(nifs): fix random oracle desc

- src/ivc/fold_relaxed_plonk_instance_chip.rs
- src/nifs/mod.rs
- src/nifs/tests.rs
- src/nifs/vanilla.rs
FoldingScheme trait is defined for both VanillaFS and (future) ProtogalaxyFS. We refactor the implementation of VanillaFS using FoldingScheme trait.
> refactor(nifs): impl VanillaFS using FS trait

- examples/sha256/main.rs
- src/ivc/incrementally_verifiable_computation.rs
- src/ivc/public_params.rs
- src/ivc/step_folding_circuit.rs
- src/nifs/vanilla.rs
- src/plonk/mod.rs
- src/poseidon/random_oracle.rs
Part of #31, impl base-case, remastering of #145
Code is ready, tests in progress
> feat(ivc): impl base case

- src/ivc/incrementally_verifiable_computation.rs
Incorporated the new random oracle design and made working checks for X{0,1}
- Add validation errors
- Rm input variables (because they don't needed in this API design)
> refactor(ivc): remaster verify

- examples/sha256/main.rs
- examples/trivial/main.rs
- src/ivc/incrementally_verifiable_computation.rs
In that case, it would be much more fair API since we can't do anything with that particular class anyway
Make all method private, but add one `pub fn fold`
> feat(ivc): impl `pub fn fold` method

- src/gadgets/nonnative/bn/big_uint_mul_mod_chip/mod.rs
- src/gadgets/nonnative/bn/big_uint_mul_mod_chip/tests.rs
- src/ivc/fold_relaxed_plonk_instance_chip.rs
**Motivation**
Taked from 'table-data' branch (#170) && refactor
**Overview**
Changed the way of working with `m_bn` from assigned value to just value
> fix(bn): work with modulus directly

- src/gadgets/nonnative/bn/big_uint_mul_mod_chip/mod.rs
**Motivation**
After #147 we will have two phases of synth
- Assign work only for fixed
- Assign work only for advice
Because of that we should't use assigned fixed columns & use only original values
Taked from #170 
**Overview**
Just ignore assigned version
Now you need to keep an eye on where and what values are used to make sure that everything fits together between calculations and on-circuit validation
> fix(bn): not use assigned fixed columns

- src/ivc/instance_computation.rs
**Motivation**
N/A
**Overview**
N/A
> refactor(icomp): `C2` -> `C`

- src/ivc/incrementally_verifiable_computation.rs
**Motivation**
We only know about the first error that occurred during `verify` execution, but all of them may be important for us.
**Overview**
Collect of verification errors into vec
> feat(ivc): accum errs in `verify`

- src/ivc/step_folding_circuit.rs
**Motivation**
The intension for adding the implementation of the trait was a misunderstanding of the thesis from @chaosma 
**Overview**
Simplification, just move methods code directly into `impl Circuit`
> refactor(sfp): rm impl `StepCircuit`

- Cargo.toml
- src/polynomial/folding_poly.rs
- src/polynomial/grouped_poly.rs
- src/polynomial/mod.rs
**Motivation**
Part of #159 
**Overview**
Representation of the new structure to be used for the new `fold_transform`
> feat(poly): impl `GroupedPoly`

- src/polynomial/grouped_poly.rs
**Motivation**
Creation of `GroupedPoly`
Part of #159
**Overview**
- The implementation follows the idea of `fold_transform`.
- Multiplication by `F` is implemented
- Implemented a simple test of `GroupedPoly` creation
- The plan is to add a benchmark for this function based on a real `StepFoldingCircuit` expression
> feat(poly): impl `GroupedPoly::new`

- src/plonk/eval.rs
**Motivation**
We need to ensure migration from `MultiPolynomial` to `GroupedPoly`, as part of this task the Eval trait should be extended
Part of #159
**Overview**
- Trait `Eval` is split into two traits: `GetDataForEval` + `Eval`
- The incoming polynomial type `Eval` is made generic
- The `fn eval` implementation for `MultiPolynomial` has been moved to type-specific impl
- Added blanks for calculating `GroupedPoly` & `Expression` (will be done via `EvaluationGraph`)
> feat(plonk): upd `trait Eval`

- src/plonk/mod.rs
- src/polynomial/expression.rs
- src/table/circuit_runner.rs
- src/table/constraint_system_metainfo.rs
**Motivation**
Creeping replacement of `poly` by `expr` within problem #159
**Overview**
Simple add this field from `ConstraintSystemMetainfo`
> feat(plonk): `custom_gates_lookup_compressed: Expression<F>`

- src/plonk/eval.rs
**Motivation**
We need to ensure migration from `MultiPolynomial` to `GroupedPoly`, as part of this task the Eval trait should be extended
Part of #159
**Overview**
- trait Eval is split into two traits: `GetDataForEval` + `Eval`
- The incoming polynomial type `Eval` is made generic
- The `fn eval` implementation for `MultiPolynomial` has been moved to type-specific impl
- Added blanks for calculating `GroupedPoly` & `Expression` (will be done via `EvaluationGraph`)
> feat(plonk): update `trait Eval`

- src/nifs/tests.rs
**Motivation**
I needed more information to debug nifs while solving #159
The main problem was that the panics did not allow to trace the place of
occurrence in the test itself and I also wanted to trace not to the
first error, but to understand the whole context at once.
**Overview**
- Added test-specific error
- `assert_eq` -> instance of error
> test(nifs): imprv err hanling in nifs tests

- src/ivc/step_folding_circuit.rs
**Motivation**
Close #251
**Overview**
The method `without_witness` used inside V1
> feat(sfc): migrate to `floor_planner::V1`

- README.md
- examples/poseidon/main.rs
Close #247
Since the project is still in active development I think the current structure, where the architecture comes first, is reasonable, however, it is useful to provide a minimum of information needed to evaluate the API, as well as to inform the project developers about additional tools that we use. 
Also, we can discuss whether or not we should add a patch at this point about the limits that are imposed on `StepCircuit`, so that no one accidentally starts bumping into our limits without knowing about them.
> docs: improve README

- benches/poseidon/main.rs
- benches/trivial/main.rs
- examples/poseidon/main.rs
- examples/trivial/main.rs
**Motivation**
After #251 we can reduce size of tables
**Overview**
N/A
> feat: reduce `k_circuit_table_size` in examples

- src/polynomial/mod.rs
- src/polynomial/univariate.rs
**Motivation**
Close #256
**Overview**
- I'm using `Box<[_]>` as the content is not expected to change.
> feat(poly): impl univariate poly eval

- src/nifs/protogalaxy.rs
- src/nifs/protogalaxy/mod.rs
- src/nifs/protogalaxy/pow_i.rs
**Motivation**
Close #257
**Overview**
- Created a new module for `pow_i` relation calculations, calculations are done lazily, degrees are calculated once.
- protogalaxy is allocated to the module-folder
> feat(nifs): impl `protogalaxy::pow_i`

- .cargo/config.toml
- Cargo.toml
- README.md
- examples/cli.rs
**Motivaion**
Generalized Implementation #272
Part of #249 
**Overview**
Thanks to cli+dhat we can now run any test cases and measure any memory usage
> feat(example): cli with dhat mem-profiling

- src/polynomial/expression.rs
- src/polynomial/lagrange.rs
- src/polynomial/mod.rs
**Motivation**
Close #255
**Overview**
N\A
> feat(poly): impl lagrange poly for cyclic group

- Cargo.toml
- benches/trivial/main.rs
- examples/sha256/main.rs
- examples/trivial/main.rs
**Motivation**
Compliance with best practices
**Overview**
- All specific dependencies (via git) are separated into tables for simplified operation
- Added authors
- Added description
- Removed unused dependencies
- Added feature comment
> refactor(toml): clean-up cargo.toml

- src/plonk/mod.rs
**Motivation**
Part of #259 & #260
**Overview**
- Implemented witness eval method, based on lazy iterator
- It is possible to use c rayon
- Note that the computation tree is built once for each gate
- It is also possible to return a non-flat structure (Iterator of iterators), but for our usecases we would have to annotate each `.flatten()` call.
> feat(plonk): impl witness calc

- src/nifs/protogalaxy/poly/mod.rs
**Motivation**
Part of #265
**Overview**
Just add interface for this function, in order to parallelize the work on this polynomial and the subsequent issues
> feat(nifs): interface for `compute_K`

- src/fft.rs
- src/nifs/protogalaxy/poly/folded_trace.rs
- src/nifs/protogalaxy/poly/mod.rs
- src/polynomial/lagrange.rs
- src/polynomial/mod.rs
- src/polynomial/univariate.rs
**Motivation**
My fixes for #292 
**Overview**
Check #292
> refactor(nifs): work with lagrange & poly_K

- src/nifs/protogalaxy/poly/mod.rs
- src/polynomial/lagrange.rs
Part of #265 
Code simplification
> refactor(lagrange): simplify eval

- src/fft.rs
- src/nifs/protogalaxy/poly/folded_trace.rs
- src/nifs/protogalaxy/poly/mod.rs
- src/polynomial/lagrange.rs
- src/polynomial/mod.rs
- src/polynomial/univariate.rs
close #265 
Add helper functions and implement `compute_K`
> feat(nifs): impl `protogalaxy::compute_K`

- src/commitment.rs
- src/nifs/vanilla.rs
- src/plonk/lookup.rs
- src/plonk/mod.rs
- src/plonk/util.rs
- src/poseidon/poseidon_hash.rs
- src/util.rs
**Motivation**
Part of #298 
**Overview**
Just more spans for detailed logic-scopes output
> feat: add more spans

- .scripts/build_profiling.py
**Motivation**
Without fields, information about span is incomplete, part of #285
**Overview**
Simply add the required fields to the output on the basis of logs
> feat(script): add span-fields to output

- src/nifs/protogalaxy/accumulator.rs
- src/nifs/protogalaxy/mod.rs
- src/plonk/mod.rs
- src/poseidon/random_oracle.rs
**Motivation**
Part of #266
**Overview**
- Present new type `Accumulator` for protogalaxy nifs
- Add the constructor-args structure for `RelaxedPlonkTrace`
> feat(nifs): `Accumulator` for protogalaxy

- examples/merkle/circuit.rs
- rust-toolchain.toml
- src/gadgets/nonnative/bn/big_uint_mul_mod_chip/mod.rs
- src/ivc/fold_relaxed_plonk_instance_chip.rs
- src/nifs/protogalaxy/mod.rs
- src/nifs/protogalaxy/tests.rs
- src/nifs/tests.rs
- src/nifs/vanilla/tests.rs
- src/plonk/mod.rs
- src/table/mod.rs
**Motivation**
Part of #266
**Overview**
A simple test for protogalaxy folding scheme
> test(nifs): test for protogalaxy

- src/nifs/protogalaxy/tests.rs
- src/nifs/vanilla/tests.rs
**Motivation**
Close #266
**Overview**
N/A
> test(nifs): impl `protogalaxy::{fibo, fibo_with_lookup}`

- src/nifs/protogalaxy/accumulator.rs
- src/nifs/protogalaxy/mod.rs
- src/nifs/protogalaxy/tests.rs
**Motivation**
Part of #267 
**Overview**
In addition to the implementation itself, the `fold_trace` code was splitted for reuse within `prove`&`verify`.
Also documentation was written for some of the `protogalaxy` methods & structs
> feat(nifs): impl protogalaxy::verify

- src/ivc/incrementally_verifiable_computation.rs
- src/nifs/mod.rs
- src/nifs/protogalaxy/mod.rs
- src/nifs/protogalaxy/tests.rs
- src/nifs/vanilla/mod.rs
- src/nifs/vanilla/tests.rs
**Motivation**
https://github.com/snarkify/sirius/pull/339#discussion_r1741373656
Part of #267 
**Overview**
- Add trait-method `IsSatAccumulator::is_sat_commit` with witness commit check
- Add trait-method `IsSatAccumulator::is_sat` with all checks included
- Impl `IsSatAccumulator::is_sat_commit` for Protogalaxy
- Migrate everywhere to `IsSatAccumulator::is_sat`
> feat(nifs): `IsSatAccumulator::is_sat_commit` for protogalaxy

- src/gadgets/nonnative/bn/big_uint_mul_mod_chip/tests.rs
- src/ivc/incrementally_verifiable_computation.rs
- src/nifs/mod.rs
- src/nifs/protogalaxy/mod.rs
- src/nifs/protogalaxy/tests.rs
- src/nifs/vanilla/mod.rs
- src/nifs/vanilla/tests.rs
- src/plonk/mod.rs
**Motivation**
Close #267
**Overview**
- impl `ProtoGalaxy::is_sat_acc`
- impl `ProtoGalaxy::is_sat_perm`
- finish tests for protogalaxy circuits
> feat(nifs): impl `protogalaxy::is_sat_acc` 

- src/ivc/fold_relaxed_plonk_instance_chip.rs
- src/ivc/incrementally_verifiable_computation.rs
- src/ivc/instance_computation.rs
- src/ivc/public_params.rs
- src/ivc/step_circuit.rs
- src/nifs/mod.rs
- src/nifs/protogalaxy/mod.rs
- src/nifs/protogalaxy/tests.rs
- src/nifs/vanilla/mod.rs
- src/nifs/vanilla/tests.rs
- src/plonk/mod.rs
- src/table/circuit_runner.rs
- src/table/tests.rs
- src/table/witness_data.rs
**Motivation**
Part of #329 
**Overview**
Previous one - #342 
Update API for `CircuitRunner` & `FoldingScheme`
> feat(nifs): support of instances in folding scheme

- src/ivc/fold_relaxed_plonk_instance_chip.rs
- src/ivc/incrementally_verifiable_computation.rs
- src/ivc/instance_computation.rs
- src/ivc/public_params.rs
- src/ivc/step_circuit.rs
- src/ivc/step_folding_circuit.rs
- src/nifs/mod.rs
- src/nifs/protogalaxy/mod.rs
- src/nifs/protogalaxy/tests.rs
- src/nifs/vanilla/mod.rs
- src/nifs/vanilla/tests.rs
- src/plonk/mod.rs
- src/table/circuit_runner.rs
- src/table/tests.rs
- src/table/witness_data.rs
**Motivation**
Part of #329
We need to add the ability to work with instance columns
**Overview**
NOTE: Update only public API, no support at any other level is implemented
Added method for `StepCircuit` and its support in `StepFoldingCircuit` and also in `IVC`
Update of `CircuitRunner` will be next PR
> feat(sc): instance column API

- examples/my_circuit.rs
- src/ivc/fold_relaxed_plonk_instance_chip.rs
- src/ivc/instance_computation.rs
- src/ivc/public_params.rs
- src/ivc/step_folding_circuit.rs
- src/nifs/protogalaxy/mod.rs
- src/nifs/protogalaxy/poly/mod.rs
- src/nifs/vanilla/accumulator.rs
- src/nifs/vanilla/mod.rs
- src/nifs/vanilla/tests.rs
- src/plonk/mod.rs
- src/plonk/util.rs
- src/sps.rs
- src/table/circuit_data.rs
- src/table/circuit_runner.rs
**Motivation**
Close #329
**Overview**
Right now all API for instances column is ready, but all work for really support it will be in the #316
> feat(plonk): support of instances

- examples/instances.rs
- src/ivc/consistency_markers_computation.rs
- src/ivc/fold_relaxed_plonk_instance_chip.rs
- src/ivc/incrementally_verifiable_computation.rs
- src/ivc/mod.rs
- src/ivc/public_params.rs
- src/ivc/step_folding_circuit.rs
- src/nifs/protogalaxy/mod.rs
- src/nifs/vanilla/mod.rs
- src/plonk/mod.rs
- src/plonk/util.rs
**Motivation**
Part of #316 
**Overview**
As part of this PR have been prepared a permutation check for any number of instances. IVC with step_count > 1 - now is not working, because lack of instances folding in `StepFoldinCircuit`
> feat(plonk): support of instances in perm

- examples/instances.rs
- src/ivc/fold_relaxed_plonk_instance_chip.rs
- src/ivc/instances_accumulator_computation.rs
- src/nifs/vanilla/accumulator.rs
**Movation**
Part of #316
**Overview**
- Just makes it easy to break the circuit and make sure all works
- rename `fold_*` into `absorb_in`
> feat(example): instance example for manual test

- examples/instances.rs
- src/ivc/incrementally_verifiable_computation.rs
- src/nifs/mod.rs
- src/nifs/protogalaxy/mod.rs
- src/nifs/protogalaxy/tests.rs
- src/nifs/vanilla/accumulator.rs
- src/nifs/vanilla/mod.rs
- src/nifs/vanilla/tests.rs
- src/plonk/mod.rs
**Motivation**
Close #316
**Overview**
- Refactored `vanilla::is_sat` error handling into `vanilla` module
- Added `is_sat_pub_instances` method for public input verification
- Updated `instance` example doc
- Add accumulation check into `IVC`
> feat(nifs): impl pub instances check

- src/ivc/consistency_markers_computation.rs
- src/ivc/sangria/fold_relaxed_plonk_instance_chip.rs
- src/main_gate.rs
**Motivation**
Fix lack of API for assign adivce/fixed point in `CyclicAssignor`
**Overview**
N/A
> feat(main_gate): impl `CyclicAssigner::assign_next_point`

- rust-toolchain.toml
**Motivation**
Rust-toolchain version update
**Overview**
N/A
> chore: bump rust-toolchain

- src/nifs/protogalaxy/mod.rs
**Motivation**
As part of implementation #361, I need to check the consistency of the generation of the challange {on,off}-circuit. For simplicity, this piece of code has been separated into a separate function
**Overview**
No functional changes, only move of challange-generation into a separate structure
> refactor(nifs): remaster challenges absorbation

- src/ivc/protogalaxy/mod.rs
**Motivation**
Part of #361
**Overview**
N/A
> feat(ivc): impl eval_vanishing_poly

- src/ivc/protogalaxy/mod.rs
- src/nifs/protogalaxy/mod.rs
**Motivation**
Part of #361
Calculateion of `e` is high-level part of protogalaxy protocol.
**Overview**
N/A
> feat(ivc): impl `protogalaxy::calculate_e`

- src/ivc/cyclefold.rs
- src/ivc/cyclefold/support_circuit.rs
- src/ivc/cyclefold/support_circuit/tiny_gate.rs
- src/ivc/mod.rs
**Motivation**
We need to implement an ecc operations for #371 within the second curve
**Overview**
Not the entire implementation is presented here, but just the first part of it to discuss the design of the constraints within the gate
> feat(ivc): impl tiny-gate-ecc

- src/ivc/cyclefold/incrementally_verifiable_computation/public_params.rs
**Motivation**
Close #372
**Overview**
Closes all cyclefold::pp functionality by adding digest counting
> feat(ivc): cyclefold public params digest

- src/ivc/cyclefold/support_circuit/mod.rs
- src/ivc/cyclefold/support_circuit/tiny_gate.rs
**Motivation**
Previously, methods unavailable for zero values were used, but the initial accumulator values are zero
**Overview**
The target methods have been changed, and comments and `inspect_err` for all methods have been added for easier debugging
> fix(ivc): cyclefold::support_circuit support zero

- examples/cli.rs
- examples/cyclefold_poseidon.rs
- examples/cyclefold_trivial/main.rs
- examples/sangria_poseidon.rs
- examples/sangria_trivial/main.rs
For test cyclefold
Improved built-in cli, for testing and comparing different IVC
> feat(examples): impl cyclefold mode in cli

- src/nifs/protogalaxy/poly/folded_witness.rs
**Motivation**
Acceleration cyclefold::ivc
**Overview**
Executed a basic tip for speeding up is to self-separate a large amount of work into chunk to have fewer tasks rayon
```terminal
cyclefold_ivc_of_poseidon/fold_1_step
time:   [19.980 s 20.171 s 20.350 s]
change: [-3.5234% -2.1196% -0.6568%] (p = 0.02 < 0.10)
Change within noise threshold.
```
> perf(nifs): rayon-chunks for `cyclefold::fold_witness`

- examples/merkle/ipa.rs
- examples/merkle/kzg.rs
- examples/merkle/main.rs
- rust-toolchain.toml
- src/fft.rs
**Motivation**
To use it as additional benchmark for compare IVCs
**Overview**
Just add cyclefold as option for merkle-cli example
> feat(example): cyclefold in merkle-cli
